# .gitlab-ci.yml

stages:
  - test

variables:
  MARIADB_ALLOW_EMPTY_PASSWORD: 1
  MARIADB_USER: 'user'
  MARIADB_PASSWORD: 'password'
  MARIADB_ROOT_PASSWORD: 'password'


before_script:
  # Update packages and install required software
  - apt-get update -yqq
  - apt-get install -yqq git unzip
  - apt-get install -yqq telnet  
  # Install Composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  # Install PHP extensions
  - docker-php-ext-install pdo_mysql

  # Setup the application
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

# PHPUnit Test
phpunit_test:
  stage: test
  image: php:8.2
  services:
    - name: mariadb:latest
      alias: mariadb

  script:
    - sleep 10
    - telnet mariadb 3306
    # Prepare the Symfony environment
    - php bin/console doctrine:database:create --env=dev
    - php bin/console doctrine:schema:create --env=dev
    - php bin/console doctrine:fixtures:load -n --env=dev

    # Run PHPUnit tests
    - ./vendor/bin/phpunit --coverage-text
