# .gitlab-ci.yml

stages:
  - test

variables:
  MYSQL_DATABASE: root
  MYSQL_ROOT_PASSWORD: password

before_script:
  # Update packages and install required software
  - apt-get update -yqq
  - apt-get install -yqq git unzip

  # Install Composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  # Install PHP extensions
  - docker-php-ext-install pdo_mysql

  # Setup the application
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

# PHPUnit Test
phpunit_test:
  stage: test
  image: php:8.2
  services:
    - name: mariadb:latest
      alias: mariadb

  script:
    - apt-get install -yqq netcat
    - while ! nc -z mariadb 3306; do sleep 1; done

    # Prepare the Symfony environment
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load -n --env=test

    # Run PHPUnit tests
    - ./vendor/bin/phpunit --coverage-text
